
title: Officially Awesome
email: hello@officiallyawesome.online
description: >- # this means to ignore newlines until "baseurl:"
  Awesome resources for awesome officials

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://officiallyawesome.woozle.uk" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: jekyllrb
github_username:  officiallyawesome

# Build settings
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
